openapi: 3.0.3
info:
  title: Request Body Shape Test
  version: 1.0.0

paths:
  /optional-array-nullable:
    post:
      operationId: optionalArrayNullable
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: array
              nullable: true
              items:
                type: string
                nullable: false
      responses:
        '204':
          description: No Content

  /array-nullable:
    post:
      operationId: arrayNullable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              nullable: true
              items:
                type: string
                nullable: false
      responses:
        '204':
          description: No Content

  /array-not-nullable:
    post:
      operationId: arrayNotNullable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              nullable: false
              items:
                type: string
                nullable: false
      responses:
        '204':
          description: No Content

  /object-keys-additional-properties-false:
    post:
      operationId: objectKeysAdditionalPropertiesFalse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              nullable: false
              required:
                - requiredNullableString
                - requiredNotNullableString
              additionalProperties: false
              properties:
                requiredNullableString:
                  type: string
                  nullable: true
                requiredNotNullableString:
                  type: string
                  nullable: false
                optionalNullableString:
                  type: string
                  nullable: true
                optionalNotNullableString:
                  type: string
                  nullable: false
      responses:
        '204':
          description: No Content

  /nullable-object-keys-additional-properties-false:
    post:
      operationId: nullableObjectKeysAdditionalPropertiesFalse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              nullable: true
              required:
                - requiredNullableString
                - requiredNotNullableString
              additionalProperties: false
              properties:
                requiredNullableString:
                  type: string
                  nullable: true
                requiredNotNullableString:
                  type: string
                  nullable: false
                optionalNullableString:
                  type: string
                  nullable: true
                optionalNotNullableString:
                  type: string
                  nullable: false
      responses:
        '204':
          description: No Content

  /string-no-format-nullable:
    post:
      operationId: stringNoFormatNullable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              nullable: true
      responses:
        '204':
          description: No Content

  /string-no-format-not-nullable:
    post:
      operationId: stringNoFormatNotNullable
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              nullable: false
      responses:
        '204':
          description: No Content

  /composite-object:
    post:
      operationId: compositeObject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              nullable: false
              required:
                - arrayNullableItemsNullable
                - arrayNullableItemsNotNullable
                - arrayNotNullableItemsNullable
                - arrayNotNullableItemsNotNullable
                - objectAdditionalPropertiesTrue
                - objectAdditionalPropertiesSchema
                - objectAdditionalPropertiesImplicit
                - stringFormatNullable
                - stringFormatNotNullable
                - numberNullable
                - numberNotNullable
                - boolNullable
                - boolNotNullable
              additionalProperties: false
              properties:
                arrayNullableItemsNullable:
                  type: array
                  nullable: true
                  items:
                    type: string
                    nullable: true
                arrayNullableItemsNotNullable:
                  type: array
                  nullable: true
                  items:
                    type: string
                    nullable: false
                arrayNotNullableItemsNullable:
                  type: array
                  nullable: false
                  items:
                    type: string
                    nullable: true
                arrayNotNullableItemsNotNullable:
                  type: array
                  nullable: false
                  items:
                    type: string
                    nullable: false
                objectAdditionalPropertiesTrue:
                  type: object
                  nullable: false
                  additionalProperties: true
                  properties:
                    known:
                      type: string
                      nullable: false
                objectAdditionalPropertiesSchema:
                  type: object
                  nullable: false
                  additionalProperties:
                    type: string
                    nullable: false
                  properties:
                    known:
                      type: string
                      nullable: false
                objectAdditionalPropertiesImplicit:
                  type: object
                  nullable: false
                  properties:
                    known:
                      type: string
                      nullable: false
                stringFormatNullable:
                  type: string
                  format: date-time
                  nullable: true
                stringFormatNotNullable:
                  type: string
                  format: date-time
                  nullable: false
                numberNullable:
                  type: number
                  nullable: true
                numberNotNullable:
                  type: number
                  nullable: false
                boolNullable:
                  type: boolean
                  nullable: true
                boolNotNullable:
                  type: boolean
                  nullable: false
      responses:
        '204':
          description: No Content
