//nolint:godoclint // Private product-graph vocabulary is local to certification.
package patterngenerator

import (
	"encoding/binary"
	"slices"

	"pgregory.net/rapid"
)

const (
	productStateBaseBytes = 48
	productEdgeBytes      = 40
)

type productTuple struct {
	patterns []uint32
	length   int
}

type productEdge struct {
	next  uint32
	bytes byteSet
}

type productState struct {
	edges     []productEdge
	accepting bool
}

type productGraph struct {
	states   []productState
	shortest []int
}

type graphBudget struct {
	limits      constructionLimits
	states      uint64
	transitions uint64
	bytes       uint64
	work        uint64
}

type drawAction struct {
	stop  bool
	next  uint32
	bytes []byte
}

//nolint:cyclop,gocognit // Exhaustive exploration keeps every resource check at its allocation site.
func buildProductGraph(
	machines []*dfa,
	requirements []Requirement,
	minLength int,
	maxLength *int,
	limits constructionLimits,
) (*productGraph, error) {
	if uint64(minLength) > limits.generatedBytes {
		return nil, limitError(
			"output", "generated bytes", limits.generatedBytes, uint64(minLength),
		)
	}

	effectiveMaximum := maxLength
	if maxLength != nil && uint64(*maxLength) > limits.generatedBytes {
		effectiveMaximum = nil
	}

	work := &graphBudget{limits: limits}
	initial := productTuple{patterns: make([]uint32, len(machines))}
	tuples := []productTuple{initial}
	keys := map[string]uint32{productKey(initial): 0}
	graph := &productGraph{}

	if err := work.addState(len(machines)); err != nil {
		return nil, err
	}

	graph.states = append(graph.states, productState{
		accepting: productAccepts(initial, machines, requirements, minLength, effectiveMaximum),
	})

	for current := 0; current < len(tuples); current++ {
		tuple := tuples[current]
		if effectiveMaximum != nil && tuple.length == *effectiveMaximum {
			continue
		}

		if err := work.addTransitions(asciiAlphabetSize); err != nil {
			return nil, err
		}

		if err := work.addCertificationWork(asciiAlphabetSize); err != nil {
			return nil, err
		}

		byTarget := make(map[uint32]byteSet)

		for value := range asciiAlphabetSize {
			next := productTuple{
				patterns: make([]uint32, len(machines)),
				length:   nextLength(tuple.length, minLength, effectiveMaximum),
			}
			for index, machine := range machines {
				next.patterns[index] = machine.states[tuple.patterns[index]].transitions[value]
			}

			key := productKey(next)

			nextID, ok := keys[key]
			if !ok {
				nextID = uint32(len(tuples))
				if err := work.addState(len(machines)); err != nil {
					return nil, err
				}

				keys[key] = nextID

				tuples = append(tuples, next)
				graph.states = append(graph.states, productState{
					accepting: productAccepts(next, machines, requirements, minLength, effectiveMaximum),
				})
			}

			set := byTarget[nextID]
			set.add(byte(value))
			byTarget[nextID] = set
		}

		targets := make([]uint32, 0, len(byTarget))
		for target := range byTarget {
			targets = append(targets, target)
		}

		slices.Sort(targets)

		if err := work.addGraphBytes(uint64(len(targets)) * productEdgeBytes); err != nil {
			return nil, err
		}

		graph.states[current].edges = make([]productEdge, 0, len(targets))
		for _, target := range targets {
			graph.states[current].edges = append(graph.states[current].edges, productEdge{
				next: target, bytes: byTarget[target],
			})
		}
	}

	if err := graph.certify(work); err != nil {
		return nil, err
	}

	if graph.shortest[0] < 0 {
		return nil, ErrNoValues
	}

	return graph, nil
}

//nolint:cyclop // Reverse reachability and shortest-distance certification are one atomic proof.
func (graph *productGraph) certify(work *graphBudget) error {
	reverse := make([][]uint32, len(graph.states))
	for source, state := range graph.states {
		for _, edge := range state.edges {
			if err := work.addCertificationWork(1); err != nil {
				return err
			}

			reverse[edge.next] = append(reverse[edge.next], uint32(source))
		}
	}

	graph.shortest = make([]int, len(graph.states))
	for index := range graph.shortest {
		graph.shortest[index] = -1
	}

	queue := make([]uint32, 0)

	for state, item := range graph.states {
		if !item.accepting {
			continue
		}

		if err := work.addCertificationWork(1); err != nil {
			return err
		}

		graph.shortest[state] = 0
		queue = append(queue, uint32(state))
	}

	for head := 0; head < len(queue); head++ {
		state := queue[head]
		for _, predecessor := range reverse[state] {
			if err := work.addCertificationWork(1); err != nil {
				return err
			}

			if graph.shortest[predecessor] >= 0 {
				continue
			}

			graph.shortest[predecessor] = graph.shortest[state] + 1
			queue = append(queue, predecessor)
		}
	}

	return nil
}

func (graph *productGraph) generator(limits constructionLimits) (*rapid.Generator[string], error) {
	shortest := graph.shortest[0]

	extraMaximum, err := outputAllowance(uint64(shortest), limits)
	if err != nil {
		return nil, err
	}

	return rapid.Custom(func(t *rapid.T) string {
		state := uint32(0)
		value := make([]byte, 0, shortest+int(extraMaximum))
		extra := rapid.IntRange(0, int(extraMaximum)).Draw(t, "extra length")
		fuel := shortest + extra

		for {
			actions := graph.legalActions(state, fuel)

			action := rapid.SampledFrom(actions).Draw(t, "action")
			if action.stop {
				return string(value)
			}

			value = append(value, rapid.SampledFrom(action.bytes).Draw(t, "byte"))
			state = action.next
			fuel--
		}
	}), nil
}

func outputAllowance(shortest uint64, limits constructionLimits) (uint64, error) {
	if shortest > limits.generatedBytes {
		return 0, limitError(
			"output", "generated bytes", limits.generatedBytes, shortest,
		)
	}

	return min(limits.extraLength, limits.generatedBytes-shortest), nil
}

func (graph *productGraph) legalActions(state uint32, fuel int) []drawAction {
	actions := make([]drawAction, 0, len(graph.states[state].edges)+1)
	if graph.states[state].accepting {
		actions = append(actions, drawAction{stop: true})
	}

	if fuel == 0 {
		return actions
	}

	edges := append([]productEdge(nil), graph.states[state].edges...)
	slices.SortFunc(edges, func(left productEdge, right productEdge) int {
		leftDistance := graph.shortest[left.next]

		rightDistance := graph.shortest[right.next]
		if comparison := leftDistance - rightDistance; comparison != 0 {
			return comparison
		}

		return int(left.bytes.values()[0]) - int(right.bytes.values()[0])
	})

	for _, edge := range edges {
		distance := graph.shortest[edge.next]
		if distance < 0 || distance > fuel-1 {
			continue
		}

		actions = append(actions, drawAction{next: edge.next, bytes: edge.bytes.values()})
	}

	return actions
}

func productAccepts(
	tuple productTuple,
	machines []*dfa,
	requirements []Requirement,
	minLength int,
	maxLength *int,
) bool {
	if tuple.length < minLength || maxLength != nil && tuple.length > *maxLength {
		return false
	}

	for index, machine := range machines {
		if machine.states[tuple.patterns[index]].accepting != requirements[index].WantMatch {
			return false
		}
	}

	return true
}

func nextLength(current int, minLength int, maxLength *int) int {
	if maxLength != nil {
		return current + 1
	}

	if current >= minLength {
		return minLength
	}

	return current + 1
}

func productKey(tuple productTuple) string {
	key := binary.AppendUvarint(nil, uint64(tuple.length)+1)
	for _, state := range tuple.patterns {
		key = binary.AppendUvarint(key, uint64(state)+1)
	}

	return string(key)
}

func (work *graphBudget) addState(patterns int) error {
	if err := addLimited(
		&work.states,
		1,
		work.limits.productStates,
		"product construction",
		"reachable product states",
	); err != nil {
		return err
	}

	return work.addGraphBytes(productStateBaseBytes + uint64(patterns)*4)
}

func (work *graphBudget) addTransitions(amount uint64) error {
	return addLimited(
		&work.transitions,
		amount,
		work.limits.productTransitions,
		"product construction",
		"reachable product transitions",
	)
}

func (work *graphBudget) addGraphBytes(amount uint64) error {
	return addLimited(
		&work.bytes,
		amount,
		work.limits.graphBytes,
		"product construction",
		"graph bytes",
	)
}

func (work *graphBudget) addCertificationWork(amount uint64) error {
	return addLimited(
		&work.work,
		amount,
		work.limits.certificationWork,
		"certification",
		"certification work",
	)
}

func addLimited(
	counter *uint64,
	amount uint64,
	maximum uint64,
	phase string,
	limit string,
) error {
	if amount > ^uint64(0)-*counter {
		return limitError(phase, limit, maximum, ^uint64(0))
	}

	observed := *counter + amount
	if observed > maximum {
		return limitError(phase, limit, maximum, observed)
	}

	*counter = observed

	return nil
}
