reviews:
  path_filters:
    - "**"
    - "!vendor/**"
    - "!**/vendor/**"
    - "!dist/**"
    - "!**/dist/**"
    - "!build/**"
    - "!**/build/**"
    - "!coverage/**"
    - "!**/coverage/**"
    - "!**/*.pb.go"
    - "!**/*_generated.go"
    - "!**/*.gen.go"
